services:
  rust:
    build: .
    volumes:
      - .:/workspace
    command: sleep infinity

  mysql:
    image: mysql:9.2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: Dex
